/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoyuan.web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

/** 
 * MyEclipse Struts
 * Creation date: 08-24-2015
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class AlbumAction extends DispatchAction {
	
	public ActionForward myAlbumUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goMyAlbumUI");
	}
	//跳转到添加一个相册的页面 
	//addAlbumUI  addPhotoUI
	public ActionForward addAlbumUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goAddAlbumUI");
	}
	//跳转到给相册添加图片的页面
	public ActionForward addPhotoUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goAddPhotoUI");
	}
	//跳转到当前这个相册goOneAlbumUI  
	public ActionForward oneAlbumUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goOneAlbumUI");
	}
	//跳转到一张张的观看该相册图片的界面onePhotoUI
	public ActionForward onePhotoUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goOnePhotoUI");
	}
	
}