/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoyuan.web.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;
import org.apache.struts.upload.FormFile;

import com.xiaoyuan.domain.Users;
import com.xiaoyuan.service.inter.UserServiceInter;
import com.xiaoyuan.utils.MyTools;
import com.xiaoyuan.web.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-23-2015
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class ProfileAction extends DispatchAction {
	private UserServiceInter userService;
	
	public void setUserService(UserServiceInter userService) {
		this.userService = userService;
	}
	public ActionForward goHomePageUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goHomePageUI");
	}
	//跳转到上传头像界面goUploadPhotoUI
	public ActionForward goUploadPhotoUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		return mapping.findForward("goUploadPhotoUI");
	}
	//真正上传一个头像
	public ActionForward uploadPhoto(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		Users loginUser=(Users) request.getSession().getAttribute("loginuser");

		UserForm userForm=(UserForm)form;

		FormFile myPhoto=userForm.getMyphoto();
		//把该头像上传到服务器的某个目录下【xiaoyuanwang/images/用户编号/head/头像图片】
		/**
		 * 
		 */
		String newHeadPhoto=MyTools.uploadHead(request,myPhoto, loginUser.getId()+"");
		
		//得到当前用户【从session中取出】
	
//		System.out.println(myPhoto.getFileName());
		loginUser.setPhoto(newHeadPhoto);
		userService.update(loginUser);
		return mapping.findForward("goUploadPhotoUI");
	}
	
	
}