/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.xiaoyuan.web.action;

import java.util.Date;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.xiaoyuan.domain.University;
import com.xiaoyuan.domain.Users;
import com.xiaoyuan.domain.Useruniversity;
import com.xiaoyuan.service.inter.CountryServiceInter;
import com.xiaoyuan.service.inter.ProvinceServiceInter;
import com.xiaoyuan.service.inter.UniversityServiceInter;
import com.xiaoyuan.service.inter.UserServiceInter;
import com.xiaoyuan.service.inter.UserUniversityServiceInter;
import com.xiaoyuan.web.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 08-20-2015
 * 
 * XDoclet definition:
 * @struts.action parameter="flag"
 */
public class RegisterAction extends DispatchAction {
	
	
	@Resource
	private CountryServiceInter coutryService;
	private ProvinceServiceInter provinceService;
	private UniversityServiceInter universityService;
	private UserServiceInter userService;
	private UserUniversityServiceInter userUniversityService;
	
 	
	public void setUserService(UserServiceInter userService) {
		this.userService = userService;
	}

	public void setUserUniversityService(
			UserUniversityServiceInter userUniversityService) {
		this.userUniversityService = userUniversityService;
	}

	public void setUniversityService(UniversityServiceInter universityService) {
		this.universityService = universityService;
	}

	public void setProvinceService(ProvinceServiceInter provinceService) {
		this.provinceService = provinceService;
	}

	public void setCoutryService(CountryServiceInter coutryService) {
		this.coutryService = coutryService;
	}

	//跳转到注册页面UI user interface(界面)
	public ActionForward registUI(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		//准备数据供用户选择大学时使用
		//国家
		request.setAttribute("countrylist",coutryService.getResult("from Country", null));
		//直辖市
		//省和直辖市的信息（默认显示中国
		request.setAttribute("provincelist", provinceService.getResult("from Province where country.id=?",new Object[]{new Integer(1)}));
		//大学名字（默认显示北京）
		
		request.setAttribute("universitylist", universityService.getResult("from University where province.id=? and country.id=?",new Object[]{new Integer(1),new Integer(1)}));
		//点击注册则跳转到注册页面
		return mapping.findForward("registUI");
	}
	//注册用户。真的添加到数据库
	public ActionForward registUser(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		// TODO Auto-generated method stub
		
		//从该action对应的表单中，取出数据
		UserForm userForm=(UserForm)form;
		//取出信息 目的是把用户保存
		Users user=new Users();
		user.setEmail(userForm.getEmail());
		user.setLoginDate(new java.util.Date());
		user.setName(userForm.getName());
		user.setPwd(userForm.getPwd());
		user.setRegisterDate(new java.util.Date());
		user.setSex(userForm.getSex());
		
		//先得到该用户的大学对象
//		System.out.println("测试");
//		System.out.println(userForm.getUniversityId());
		University university=(University)universityService.findById(University.class,Integer.valueOf(userForm.getUniversityId()));
		//创建该用户对应的用户大学记录
		//取出信息 目的是把用户大学信息保存
//		System.out.println("测试通过");
		Useruniversity userUniversity=new Useruniversity();
		
		userUniversity.setUsers(user);
		userUniversity.setUniversity(university);
		userUniversity.setUserType(userForm.getUserType());
		
		//保存用户
		userService.save(user);
		userUniversityService.save(userUniversity);
		
		//点击注册则跳转到home.jsp页面
		return mapping.findForward("registSuccess");
	}
}